server:
  port:
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1770000
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    mapper-locations:
      - classpath:mapper/*.xml