package io.github.ecustse211;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@RestController
@SpringBootApplication
public class EcustSe211Application {

	public static void main(String[] args) {
		SpringApplication.run(EcustSe211Application.class, args);
	}

	@GetMapping("/")
	public String index(){
		return "ok";
	}
}
